-- PostgreSQL Schema for "المعهد الأول" (The First Institute)

-- Best practice: Use extensions for added functionality, like UUIDs.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enum type for user roles to ensure data consistency.
CREATE TYPE user_role AS ENUM ('admin', 'teacher', 'student');

-- Main table for all users, leveraging the role-based system.
CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name VARCHAR(255) NOT NULL,
    -- The login code is unique for each user.
    login_code VARCHAR(100) UNIQUE NOT NULL,
    role user_role NOT NULL,
    -- Timestamps for tracking user creation and updates.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to store class information.
CREATE TABLE classes (
    class_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    class_name VARCHAR(255) NOT NULL,
    -- The teacher who is responsible for this class.
    teacher_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    -- Timestamps for tracking class creation and updates.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Junction table to manage student enrollments in classes (many-to-many relationship).
CREATE TABLE enrollments (
    enrollment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    class_id UUID NOT NULL REFERENCES classes(class_id) ON DELETE CASCADE,
    -- Flag to indicate if the student is new to this class.
    is_new BOOLEAN DEFAULT TRUE,
    -- Timestamps for tracking enrollment.
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Ensure a student can only be enrolled once in the same class.
    UNIQUE (student_id, class_id)
);

-- Table to store information about each lecture/session.
CREATE TABLE lectures (
    lecture_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    class_id UUID NOT NULL REFERENCES classes(class_id) ON DELETE CASCADE,
    lecture_title VARCHAR(255) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    -- Status can be 'scheduled', 'live', 'completed', 'paused'.
    status VARCHAR(50) DEFAULT 'scheduled',
    -- The report generated by the teacher after the lecture.
    report TEXT
);

-- Table for storing chat messages for each lecture.
CREATE TABLE chat_messages (
    message_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    lecture_id UUID NOT NULL REFERENCES lectures(lecture_id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    message_content TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to store links to lecture recordings.
CREATE TABLE lecture_recordings (
    recording_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    lecture_id UUID NOT NULL REFERENCES lectures(lecture_id) ON DELETE CASCADE,
    -- URL or path to the stored recording file.
    recording_url TEXT NOT NULL,
    -- Timestamps for tracking recording creation.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to manage student grades for different classes.
CREATE TABLE grades (
    grade_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    class_id UUID NOT NULL REFERENCES classes(class_id) ON DELETE CASCADE,
    -- e.g., 'Midterm Exam', 'Final Project', 'Homework 1'.
    assessment_name VARCHAR(255) NOT NULL,
    -- The grade can be a numeric value or a letter (e.g., 'A+').
    grade_value VARCHAR(50) NOT NULL,
    -- Timestamps for tracking grade creation and updates.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- A student should have a unique grade for each assessment in a class.
    UNIQUE (student_id, class_id, assessment_name)
);

-- Indexes to improve query performance on frequently searched columns.
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_login_code ON users(login_code);
CREATE INDEX idx_classes_teacher_id ON classes(teacher_id);
CREATE INDEX idx_enrollments_student_id ON enrollments(student_id);
CREATE INDEX idx_enrollments_class_id ON enrollments(class_id);
CREATE INDEX idx_lectures_class_id ON lectures(class_id);
CREATE INDEX idx_chat_messages_lecture_id ON chat_messages(lecture_id);
CREATE INDEX idx_grades_student_id ON grades(student_id);
CREATE INDEX idx_grades_class_id ON grades(class_id);

-- A trigger to automatically update the 'updated_at' timestamp on any change.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply the trigger to all tables that have the 'updated_at' column.
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_classes_updated_at BEFORE UPDATE ON classes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_grades_updated_at BEFORE UPDATE ON grades FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
