import 'package:flutter/material.dart';
import 'package:frontend/features/auth/presentation/screens/login_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:frontend/core/services/notification_service.dart';
import 'firebase_options.dart'; // To be generated by FlutterFire CLI

Future<void> main() async {
  // 1. ضمان تهيئة بيئة فلاتر قبل أي شيء
  WidgetsFlutterBinding.ensureInitialized();

  // --- التعديل الجراحي: حماية عملية التهيئة ---
  // الهدف: منع أي خطأ في Firebase من إيقاف تشغيل التطبيق (حل مشكلة الشاشة البيضاء)
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } else {
      // في حالة Hot Restart، فايربيز يعمل بالفعل، لا داعي لإعادة التهيئة
      print('⚠️ Firebase is already initialized.');
    }

    // محاولة تهيئة الإشعارات (فقط إذا نجح فايربيز أو كان يعمل مسبقاً)
    await NotificationService().initialize();
  } catch (e) {
    // التقاط الخطأ وطباعته بدلاً من السماح له بتحطيم التطبيق
    print("❌ Critical Initialization Error (App will continue): $e");
  }
  // --- نهاية التعديل ---

  // هذا السطر سيتم تنفيذه الآن في جميع الأحوال، مما يضمن اختفاء الشاشة البيضاء
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'المعهد الأول',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        // Basic RTL support for Arabic text
        scaffoldBackgroundColor: Colors.grey[50],
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.blue,
          foregroundColor: Colors.white,
        ),
        textTheme: const TextTheme(
          bodyMedium: TextStyle(fontFamily: 'Roboto'), // Example font
        ),
      ),
      // Set the initial route to the login screen
      home: LoginScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
